name: Deploy Laravel Backend to cPanel

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Install Composer Dependencies
        working-directory: backend
        run: composer install --no-dev --optimize-autoloader

      - name: Generate Production Env File
        working-directory: backend
        run: |
          echo "APP_NAME=Hometronix" > .env
          echo "APP_ENV=production" >> .env
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "APP_DEBUG=false" >> .env
          echo "APP_URL=https://api.pms.webtechassets.com" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASS }}" >> .env

      - name: Zip Backend
        working-directory: backend
        run: zip -r ../backend.zip .

      - name: Upload via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          protocol: ftps
          local-dir: "backend"
          server-dir: ${{ secrets.BACKEND_REMOTE_DIR }}
          dangerous-clean-slate: true
